# Generated by Django 6.0.6 on 2026-08-15 10:39

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_post_published_alter_post_reading_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 8, 15, 10, 39, 49, 432281, tzinfo=datetime.timezone.utc)),
        ),
    ]
