# Generated by Django 6.1 on 2026-08-18 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 18, 15, 49, 15, 801026, tzinfo=datetime.timezone.utc)),
        ),
    ]
