# Generated by Django 6.1 on 2026-08-18 15:58

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_comment_created_alter_comment_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 8, 18, 15, 58, 47, 607087, tzinfo=datetime.timezone.utc)),
        ),
    ]
