# Generated by Django 6.1 on 2026-08-18 15:59

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 8, 18, 15, 59, 24, 277869, tzinfo=datetime.timezone.utc)),
        ),
    ]
