# Generated by Django 6.1 on 2026-08-18 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_comment_created_alter_comment_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 18, 16, 1, 29, 831327, tzinfo=datetime.timezone.utc)),
        ),
    ]
