# Generated by Django 6.1 on 2026-08-18 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 18, 17, 0, 36, 839980, tzinfo=datetime.timezone.utc)),
        ),
    ]
