# Generated by Django 6.0.6 on 2026-08-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_comment_created_alter_comment_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('created',), 'verbose_name': ' تصویر ها ', 'verbose_name_plural': ' تصویر ها '},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='blog_image_created_1ba45b_idx'),
        ),
    ]
